name: rng-service
containers:
  - Dockerfile

profiles:
   dev:
      app_name : rng-service
      namespace: dev
      container_limit_cpu: 500m
      container_limit_memory: 500Mi
      container_requests_cpu: 100m
      container_requests_memory: 128Mi
